CREATE TABLE schools AS
SELECT *
FROM read_csv('data/hd2023-utf8.csv',
    header=true,
    delim=',',
    quote='"',
    columns={
        'UNITID': 'INTEGER',
        'INSTNM': 'VARCHAR(120)',
        'IALIAS': 'VARCHAR(2000)',
        'ADDR': 'VARCHAR(100)',
        'CITY': 'VARCHAR(30)',
        'STABBR': 'VARCHAR(2)',
        'ZIP': 'VARCHAR(10)',
        'FIPS': 'NUMERIC',
        'OBEREG': 'NUMERIC',
        'CHFNM': 'VARCHAR(50)',
        'CHFTITLE': 'VARCHAR(50)',
        'GENTELE': 'VARCHAR(15)',
        'EIN': 'VARCHAR(9)',
        'UEIS': 'VARCHAR(2000)',
        'OPEID': 'VARCHAR(8)',
        'OPEFLAG': 'NUMERIC',
        'WEBADDR': 'VARCHAR(150)',
        'ADMINURL': 'VARCHAR(200)',
        'FAIDURL': 'VARCHAR(200)',
        'APPLURL': 'VARCHAR(200)',
        'NPRICURL': 'VARCHAR(200)',
        'VETURL': 'VARCHAR(200)',
        'ATHURL': 'VARCHAR(200)',
        'DISAURL': 'VARCHAR(200)',
        'SECTOR': 'NUMERIC',
        'ICLEVEL': 'NUMERIC',
        'CONTROL': 'NUMERIC',
        'HLOFFER': 'NUMERIC',
        'UGOFFER': 'NUMERIC',
        'GROFFER': 'NUMERIC',
        'HDEGOFR1': 'NUMERIC',
        'DEGGRANT': 'NUMERIC',
        'HBCU': 'NUMERIC',
        'HOSPITAL': 'NUMERIC',
        'MEDICAL': 'NUMERIC',
        'TRIBAL': 'NUMERIC',
        'LOCALE': 'NUMERIC',
        'OPENPUBL': 'NUMERIC',
        'ACT': 'VARCHAR(1)',
        'NEWID': 'NUMERIC',
        'DEATHYR': 'NUMERIC',
        'CLOSEDAT': 'VARCHAR(10)',
        'CYACTIVE': 'NUMERIC',
        'POSTSEC': 'NUMERIC',
        'PSEFLAG': 'NUMERIC',
        'PSET4FLG': 'NUMERIC',
        'RPTMTH': 'NUMERIC',
        'INSTCAT': 'NUMERIC',
        'C21BASIC': 'NUMERIC',
        'C21IPUG': 'NUMERIC',
        'C21IPGRD': 'NUMERIC',
        'C21UGPRF': 'NUMERIC',
        'C21ENPRF': 'NUMERIC',
        'C21SZSET': 'NUMERIC',
        'C18BASIC': 'NUMERIC',
        'C15BASIC': 'NUMERIC',
        'CCBASIC': 'NUMERIC',
        'CARNEGIE': 'NUMERIC',
        'LANDGRNT': 'NUMERIC',
        'INSTSIZE': 'NUMERIC',
        'F1SYSTYP': 'NUMERIC',
        'F1SYSNAM': 'VARCHAR(80)',
        'F1SYSCOD': 'VARCHAR(6)',
        'CBSA': 'NUMERIC',
        'CBSATYPE': 'NUMERIC',
        'CSA': 'NUMERIC',
        'COUNTYCD': 'NUMERIC',
        'COUNTYNM': 'VARCHAR(60)',
        'CNGDSTCD': 'NUMERIC',
        'LONGITUD': 'NUMERIC',
        'LATITUDE': 'NUMERIC',
        'DFRCGID': 'NUMERIC',
        'DFRCUSCG': 'NUMERIC'
    },
    ignore_errors=true
);
